<?global $favFilter;
if (is_array($USER_FAVORITES) && count($USER_FAVORITES) > 0) {
    $favFilter = array('ID' => array_keys($USER_FAVORITES));
} else {
    $favFilter = array('ID' => false);
}

$APPLICATION->IncludeComponent(
	"bitrix:catalog.section",
	"favorites",
	array(
		"USER_FAVORITES" => $USER_FAVORITES,
		"BY_LINK" => "Y",
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "4",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_FIELD2" => "active_from",
		"ELEMENT_SORT_ORDER2" => "asc",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"INCLUDE_SUBSECTIONS" => "Y",
		"BASKET_URL" => "/personal/cart/",
		"ACTION_VARIABLE" => "",
		"PRODUCT_ID_VARIABLE" => "",
		"SECTION_ID_VARIABLE" => "",
		"PRODUCT_QUANTITY_VARIABLE" => "",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"FILTER_NAME" => 'favFilter',
		"CACHE_TYPE" => "N",
		"CACHE_TIME" =>  0,
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "N",
		"SET_TITLE" => "N",
		"SET_STATUS_404" => "N",
		"DISPLAY_COMPARE" => "Y",
		"PAGE_ELEMENT_COUNT" => "999999",
		"LINE_ELEMENT_COUNT" => "",
		"PRICE_CODE" => array(
			0 => "BASE",
			1 => "WHOLESALE",
		),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"USE_PRODUCT_QUANTITY" => "Y",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PARTIAL_PRODUCT_PROPERTIES" => "Y",
		"PRODUCT_PROPERTIES" => array(
			0 => "MANUFACTURE",
		),
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"PAGER_TITLE" => "",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "",
		"PAGER_SHOW_ALL" => "N",
		"PROPERTY_CODE" => array(
			0 => "DOCS",
			1 => "MANUFACTURE",
			2 => "ARTNUMBER",
			3 => "WEIGHT",
			4 => "DIAGONAL",
			5 => "DIAM",
			6 => "GUARANTEE",
			7 => "COUNTRY",
			8 => "POWER",
			9 => "ZIRNOST",
			10 => "KAKAO",
			11 => "KREPOST",
			12 => "MATERIAL",
			13 => "OBIEM",
			14 => "CVET",
			15 => "VOZRAST",
			16 => "SEASON",
			17 => "COLLECTION",
			18 => "USTANOVKA",
			19 => "GABARITI",
			20 => "GRUZ",
			21 => "PATRON",
			22 => "DLINA",
			23 => "EMKOST",
			24 => "ISTOCHNIK",
			25 => "SKOROST",
			26 => "VOLTE",
			27 => "NAPRIAZENIE",
			28 => "TIP",
			29 => "COKOL",
			30 => "CATEGORY",
			31 => "OUTPUT_CURRENT",
			32 => "FLEXIBLE_TRIPOD",
			33 => "DIAMETER_OF_FILTER",
			34 => "HARDDRIVE",
			35 => "PROTECTION_OF_GLARE",
			36 => "NUMBER_INPUTS",
			37 => "NUMBER_USB",
			38 => "NUMBER_CHANNELS",
			39 => "NUMBER_BURNERS",
			40 => "NUMBER_IN_MEMORY",
			41 => "WINDSHIELD_MOUNT",
			42 => "MAXIMUM_PRESSURE",
			43 => "CASE_MATERIAL",
			44 => "CLOCK",
			45 => "VOLUME_OVEN",
			46 => "OPER_MEM",
			47 => "OPERATING_SYSTEM",
			48 => "SURFACE",
			49 => "HEADSET",
			50 => "COATING",
			51 => "BATTERY",
			52 => "APERTURE",
			53 => "IMPEDANCE",
			54 => "DISPLAY_LINES",
			55 => "NFC",
			56 => "CONTROL_TYPE",
			57 => "NOISE",
			58 => "FOCAL_LENGHT",
			59 => "FORMAT_MEDIA",
			60 => "PLAYBACK_FORMATS",
			61 => "FREQUENCY_RANGE",
			62 => "SENSITIVITY",
			63 => "KEYBOARD_LANGUAGE",
		),
		"OFFERS_CART_PROPERTIES" => array(
			0 => "COLOR_REF",
			1 => "SIZES_SHOES",
			2 => "SIZES_CLOTHES",
		),
		"OFFERS_FIELD_CODE" => array(
		),
		"OFFERS_PROPERTY_CODE" => array(
			0 => "ARTNUMBER",
			1 => "COLOR_REF",
			2 => "SIZES_SHOES",
			3 => "SIZES_CLOTHES",
		),
		"OFFERS_SORT_FIELD" => "sort",
        "OFFERS_SORT_FIELD2" => "name",
        "OFFERS_SORT_ORDER" => "asc",
        "OFFERS_SORT_ORDER2" => "asc",
		"OFFERS_LIMIT" => "0",
		"SECTION_ID" => "",
		"SECTION_CODE" => "",
		"SECTION_URL" => "/catalog/#SECTION_CODE#/",
        "DETAIL_URL" => "/catalog/#SECTION_CODE#/#ELEMENT_CODE#.html",
		"CONVERT_CURRENCY" => "N",
		"HIDE_NOT_AVAILABLE" => "N",
		"LABEL_PROP" => "SALELEADER",
		"ADD_PICT_PROP" => "MORE_PHOTO",
        "ADD_VIDEO_PROP" => "MORE_VIDEO",
		"PRODUCT_DISPLAY_MODE" => "Y",
		"OFFER_ADD_PICT_PROP" => "MORE_PHOTO",
        "OFFER_ADD_VIDEO_PROP" => "MORE_VIDEO",
		"OFFER_TREE_PROPS" => array(
			0 => "ARTNUMBER",
			1 => "COLOR_REF",
			2 => "SIZES_SHOES",
			3 => "SIZES_CLOTHES",
		),
		"PRODUCT_SUBSCRIPTION" => "N",
		"SHOW_DISCOUNT_PERCENT" => "N",
		"SHOW_OLD_PRICE" => "Y",
		"ADD_TO_BASKET_ACTION" => "ADD",
		"MESS_BTN_BUY" => "",
		"MESS_BTN_ADD_TO_BASKET" => "",
		"MESS_BTN_DETAIL" => "",
		"MESS_NOT_AVAILABLE" => "",
		"TEMPLATE_THEME" => "",
		"ADD_SECTIONS_CHAIN" => "N",
		"SECTION_USER_FIELDS" => array(
		),
		"SHOW_ALL_WO_SECTION" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "N",
		"AJAX_OPTION_HISTORY" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_META_DESCRIPTION" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
	),
	false
);